### PR TITLE
Webhooks provide old data together with new data

### PR DESCRIPTION
**Pull request by timizuoebideri1**
### Fixes: #330
Add feature to Webhooks to provide both old data together with new data

### Snapshot
A Snapshot(a.k.a old data) in this context is the current serialised state of a Model instance before any modifications are made.
Calling .snapshot() on an instance saves the serialized state of that model in _prechange_snapshot
e.g
```
class Site(models.Model):
  ...

  def snapshot(self):
         self._prechange_snapshot = serialize_object(self)
```

**How snapshots are taken**
```
Site.objects.create(name="Initial Site name", slug="site-1")

obj = get_object_or_404(Site, pk=1)
obj.snapshot  # Saves a snapshot
obj.name = "Updated Site name"
obj.save()
```

**To safely get the snapshot of an Instance**
```
snapshot = getattr(obj, "_prechange_snapshot", None)
# snapshot output
 {
   "name": "Initial Site name",
   "slug": "site-1"
 }
```

### Workflow on how snapshots are taken
**Scenario 1 - Update a Site**
1. User clicks on the edit button of a Site.

2. User updates the desired fields, and clicks update. 
_A snapshot of the object is taken in `ObjectEditView.get_object()` [L291](https://github.com/nautobot/nautobot/pull/1310/files#diff-6d6d85115c2145f877fca192b072690e4d8945d576ca00bff5ad903cce84c2bcR291), This way a snapshot is taken right on time before the instance is updated_

3. webhook is triggered & the snapshot of the site instance is gotten [L38](https://github.com/nautobot/nautobot/pull/1310/files#diff-b13ba2af18422828dc8d1c2b59283e9d81044dfc3d9d6fabe042ba4a335460b1R38), and added to the request body [L45](https://github.com/nautobot/nautobot/pull/1310/files#diff-b13ba2af18422828dc8d1c2b59283e9d81044dfc3d9d6fabe042ba4a335460b1R45), [L116](https://github.com/nautobot/nautobot/pull/1310/files#diff-37ccb0d12d2ea242fbc295e9d85ecf7d8cb4ca933030c05b8aa31b65e92bb0b0R116)

```
{
    "event": "created",
    "timestamp": "2020-02-25 15:10:26.010582+00:00",
    "model": "site",
    "username": "jstretch",
    "request_id": "fdbca812-3142-4783-b364-2e2bd5c16c6a",
    "data": {
        "id": 19,
        "name": "Updated Site name",
        "slug": "site-1"
        },
        ...
    },
    "snapshot": {
        "id": 19,
        "name": "Initial Site name",
        "slug": "site-1"
        },
        ...
    }
}
```

### CODE REVIEW

**Comment by glennmatthews** [comment]
Hi @timizuoebideri1, can you provide some additional context around this design and implementation, specifically how and why it differs from the NetBox implementation of this feature (netbox-community/netbox@c6641ec)?

**Comment by timizuoebideri1** [comment]
> Hi @timizuoebideri1, can you provide some additional context around this design and implementation, specifically how and why it differs from the NetBox implementation of this feature ([netbox-community/netbox@c6641ec](https://github.com/netbox-community/netbox/commit/c6641ec))?

@glennmatthews Its mostly the same with netbox implementation, differences are the way the snapshot data was implemented.

NetBox uses pre_change & post_change in its snapshots:
```
{
    ...
    "data": {
        "id": 19,
        "name": "Updated Site name",
        "slug": "site-1"
        },
        ...
    },
    "snapshot": {
       "prechange": {
            "id": 19,
            "name": "Initial Site name",
            "slug": "site-1"
        },
       "postchange": {
            "id": 19,
            "name": "Updated Site name",
            "slug": "site-1"
        },
        ...
    }
}
```
`snapshot["post_change"]` and `data` are mostly the same, I felt it was redundant that's why I removed post_change from my implementation. I could implement it the same way netbox implemented their.

**Comment by glennmatthews** [comment]
I think the reasoning behind adding `postchange` to the snapshot data is that it's a transitional step - in 2.0 we may be able to remove `data` altogether and only have `prechange` and `postchange`. We can discuss this though.

**Comment by timizuoebideri1** [comment]
> Also, it looks like this implementation doesn't address changes made via the REST API? I think we may want to have an in-depth design discussion around this feature, possibly taking inspiration from [netbox-community/netbox#5924](https://github.com/netbox-community/netbox/pull/5924) as well - it feels to me like the snapshot logic should be part of our existing change-logging feature, rather than an addition to the specific view functions that are used to make changes.

Please take a look at the approach i took here [863580...](https://github.com/nautobot/nautobot/commit/8635802248a22f135daff86bc5aed548d7823f9c), its quite simple and straightforward.

**Comment by glennmatthews** [comment]
I'm a bit confused, sorry - are you suggesting 8635802248a as an alternative to this PR's code? Or an addition to it?

**Comment by timizuoebideri1** [comment]
> I'm a bit confused, sorry - are you suggesting [8635802](https://github.com/nautobot/nautobot/commit/8635802248a22f135daff86bc5aed548d7823f9c) as an alternative to this PR's code? Or an addition to it?

Its an alternative

**Pull request closed without merging**
