### PR TITLE
Fixed loading widget in new UI

### PR DESCRIPTION
**Pull request by DistantVoyager**
# Closes: #3742 
# What's Changed

- Centered the LoadingWidget component in UI.
- Lightened the color of the LoadingWidget text to gray-3.
- Also updated the endColor of the skeleton loading animation (when tables load) to a lighter gray so it's easier on the eyes.

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))

### CODE REVIEW

**Comment by glennmatthews** [comment]
Thanks for the pull request! I like the idea, but we may not be able to go in this direction as-is due to the need to support [custom branding](https://docs.nautobot.com/projects/core/en/stable/configuration/optional-settings/#branding_filepaths) of an installed Nautobot instance.

**Comment by bryanculver** [comment]
Thanks for the idea @DistantVoyager!

**Comment by bryanculver** [comment]
Sure! you can update and re-open.

**Review by HanlinMiao — APPROVED** [review]
Thanks for the PR! LGTM!

**Pull request merged**
