### PR TITLE
Adds Ansible Connection to the Platform type

### PR DESCRIPTION
**Pull request by jvanderaa**
### Fixes: #145 

- Fixes a couple of spelling items within the Platform
- Adds additional field within the Platform to support Ansible connection types
- This is a free form for use by users which would get mapped to the `ansible_network_os`

The purpose of this PR is to provide a capability to specifically the Ansible inventory. Many practices at the moment have setting the variable for `ansible_network_os` of Ansible with the compose feature. In the compose many will put in `platform.slug` which is not able to be used with the Ansible FQCN (`cisco.ios.ios` for example).

By having this field the `compose` function of the Nautobot Ansible Inventory plugin will then be able to be `compose: platform.ansible_connection`.

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
I thought the intention was to handle this via #4. I believe that @jfach is already looking at that issue.

**Comment by jvanderaa** [comment]
Let's take a look further. I didn't realize that it was combined into issue 4 from some of the earlier conversations. 

I'd personally like to keep it separated out as it will mean keeping the data 100% in sync with various tools. When looking at Netmiko versus Ansible driver names they are different. That there is `cisco_ios` for one name and `ios` for the other name. Do we want to have that mapped one for one via Nautobot if used as a SoT or have customized capabilities there?

**Comment by jvanderaa** [comment]
For the generic part, any thoughts? I'm keeping it specific so that an organization may have multiple methods if required. I'm not sure what else comes into play quite yet. In my mind maybe a Netmiko driver, Scrapli driver. To me this is about helping automation engine inventories. At the moment I believe Nornir works ok without additional data needed. What about Salt?

**Comment by jvanderaa** [comment]
I think tying this to the manufacturer is not a good idea. Right now for platform manufacturer is not a required field for platform. So then if someone makes Cisco IOS you would get `.cisco_ios.cisco_ios`. There may also be some name collisions in the OS level from a UI perspective that we should keep this separated.

**Comment by jathanism** [comment]
> Let's take a look further. I didn't realize that it was combined into issue 4 from some of the earlier conversations.
> 
> I'd personally like to keep it separated out as it will mean keeping the data 100% in sync with various tools. When looking at Netmiko versus Ansible driver names they are different. That there is `cisco_ios` for one name and `ios` for the other name. Do we want to have that mapped one for one via Nautobot if used as a SoT or have customized capabilities there?

I like the spirit of this, but I am not keen on adding a concrete field to the `Platform` model just to serve a single use case for a single automation platform (Ansible in this case). If we followed suit with this pattern, we'd have to end up adding concrete fields for every new automation platform or driver-based module (Netmiko, et al.).

I agree we should try to lean on #4 and try to solve this with a computed field pattern. If not, then we should think more about a "provider" or "dispatcher" pattern we've been using with other tools like Nornir that could enable support for integrating with other frameworks without requiring to hard-code support for them in the core using concrete database fields.

**Comment by jvanderaa** [comment]
I've taken a look at the start up of Computed Fields. I don't think this is the user experience that we would look at wanting to have. Having to create a largely nested Jinja template, that user experience for those just getting started is a painful thing.

First off the computed field may have some complexity in including into the nested serializer for Platform. This would be needed to be able to associate with the device when polling the devices endpoint (dcim/devices/).
 
In having a discussion with @smk4664 he brought up the idea of whether or not we could have custom fields included into the nested serializer as an alternative. If that is possible, that would cover this.

**Comment by nniehoff** [comment]
I agree with @jvanderaa on this, computed fields would be interesting here but is not realistic.  Take for example the `ansible_network_os` for Cisco IOS XR devices the value should end up to be `cisco.iosxr.iosxr` If we use computed fields we could do something like `{{ obj.manufacturer.slug }}.{{ obj.slug }}.{{ obj.slug }}` but this REQUIRES the Platform to be created with a Manufacturer of slug `cisco` and the platform slug to be `iosxr`.  It works in that case.  Now take Extreme IronWare, the computed value should be `community.network.ironware` now the computed field definition needs to be different.  I guess my point is for a computed field it would create some requirements on how the objects were created that users must adhere to and the logic for determining the computed field could be quite complex and ultimately could be different in every deployment.  On the other hand if we provide a field for an ansible value we also need to a field for cool tool xyz however the precedent is already there with the Napalm driver.

**Comment by itdependsnetworks** [comment]
Netutils provides a mappings for this exact use case, it should be fairly easy to expose this in a filter. https://github.com/networktocode/netutils/blob/develop/netutils/lib_mapper.py#L143-L167

**Comment by jedelman8** [comment]
I talked with @jvanderaa .  We are good closing this out in favor of #1083 .  There may need to be additional netutils _mappers_, but ultimately getting network-centric Jinja filters in core is going to simplify adding the Ansible connection as a computed field.

**Pull request closed without merging**
