### PR TITLE
[WIP] Introduce RestrictedQuerySet.with_related.

### PR DESCRIPTION
**Pull request by Kircheneer**
# Closes: #3734
# What's Changed

Introduced `RestrictedQuerySet.with_related` to selectively call `prefetch_related` or `select_related` depending on the kind of field that is passed.

# TODO
- [x] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Add further unit tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design
- [ ] Take CacheOps into account (possible use `prefetch_related` only as long as CacheOps is installed/enabled?)

### CODE REVIEW

**Comment by Kircheneer** [comment]
Created after some internal discussion yesterday. Looking to get some feedback before I dive into the further todo items.

**Comment by glennmatthews** [comment]
I like the idea of this a lot. I **think** we need to be careful about using `select_related` until we have fully eliminated `django-cacheops` from the picture, i.e. in 2.0?

**Comment by jathanism** [comment]
Hmmm, I like where you're going with this but I want to be doubly sure that there aren't existing patterns out there that might be more mature and tested. Again, not that this isn't a great idea, but before we introduce something new to do the model API, I want to be thorough in considering any potential side effects!

**Comment by jathanism** [comment]
Ahh I just remembered that [`graphene-django-optimizer`](https://github.com/tfoxy/graphene-django-optimizer) has some query optimization for select/prefetch related queries based on incoming query schemas. I wonder if there might be some ideas we could compare there.

**Comment by bryanculver** [comment]
Great start @Kircheneer! Going to get this into a prototype branch, for now, to hopefully be picked up again in the future. Feel free to re-fork from that branch.

**Pull request merged**
