### PR TITLE
Custom Select Validation Regex

### PR DESCRIPTION
**Pull request by josh5276**
### Fixes: #876

- [ √] Adds validation regex to the select custom field types.

#### Use-case
Outside users are given the ability to add items to custom field selections, and automation keys off of these values. Via UI or API when creating an additional custom field choice, this would add a preventative measure from adding a value that did not conform to a pre-defined validation check. 

Screen Shot 2021-10-29 at 11 20 25 AM

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Thank you!

Please add some documentation of this feature in `nautobot/docs/additional-features/custom-fields.md`. 

@Thetacz can you confirm that this solution meets your needs as described in #876?

**Comment by Thetacz** [comment]
@glennmatthews I cannot see from code where do I put the regex in, but the output looks good. Thanks.

**Comment by josh5276** [comment]
Hi @Thetacz, here is a larger screenshot showing the regular expression window.

Screen Shot 2021-11-19 at 10 40 41 PM

Once the regexp is defined, it will apply to the API as well:
```
curl -XPOST $NB_HOST/api/extras/custom-field-choices/ \
-H "Content-Type: application/json" -H "Authorization: Token $TOKEN" \
-d '{"field":"58f452b2-43e3-4762-85cb-00cafd83e1fc","value":"Value X","weight":100}'

{"__all__":["Value must match regex ^\\D+\\s+\\d got Value X."]}
```
Hope this helps!

**Comment by david-kn** [comment]
Cool - based on this + our discussion with @Thetacz and @josh5276 about this PR today, I can confirm that this PR does exactly what we were looking for :-) 
Thanks @josh5276 and @glennmatthews

**Review by glennmatthews — APPROVED** [review]

**Pull request merged**
