### PR TITLE
Add --python-ver detection to invoke command

### PR DESCRIPTION
**Pull request by jifox**
### Fixes: #163

Add automatic --python-ver parameter detection for invoke commands

Added `invoke print-python-ver` command to display 
- the detected python-version of container if only a single container is running 
- the list of python-versions if multiple containers are running

### CODE REVIEW

**Comment by jathanism** [comment]
@jifox Thanks for submitting this. I appreciate the spirit of what you're trying to do here, but I'm not happy with adding another Invoke task to do it. We actually have a pattern we've been using internally at NTC for other projects using Invoke that relies more on environment variables to make some overrides that I'd like to see if we could leverage to satisfy the concerns here.

I'll get a follow up here soon. Thanks again.

**Comment by jifox** [comment]
@jathanism The additional task `print_python_ver` was just a quick win and could be removed safely.

I intentionally do not change the invoke build|debug|start commands, so that the functionality  is compatible to current functionality and just aids on commands that make no sense to execute for a non existent container (error) like invoke cli.

**Comment by glennmatthews** [comment]
Please take a look at #180 and see if its alternate approach (controlling the Python version exclusively through environment variables) works for you. Thanks!

**Comment by jifox** [comment]
@glennmatthews I'll going to use the environment variable approach.

**Pull request closed without merging**
