### PR TITLE
Add Commit Hash on Sync Page for Git Repositories

### LINKED ISSUE #623: Git Sync - Include Commit Hash on Sync Page
### Environment
* Python version: 3.6
* Nautobot version: 1.0.3

### Proposed Functionality

Add the Git hash to the git sync output display

### Use Case

To be able to verify the commit hash matches the version that is expected for troubleshooting.

### Database Changes

None

### External Dependencies

None

### PR DESCRIPTION
**Pull request by jeffkala**
### Fixes: #<ISSUE NUMBER GOES HERE>
fixes #623 

Add an information log to sync page to be able to quickly validate git hash is accurate.

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]
Looks good! My only nitpick might be that this appears at the very end of the logs now. What do you think about possibly moving this log call up to around line 88 (between the `ensure_git_repository()` and `refresh_datasource_content()` calls) so that it appears near the beginning of the logs instead?

**Comment by jeffkala** [comment]
@glennmatthews works for me, I'll get it updated.

**Comment by jeffkala** [comment]
@glennmatthews anything else on this?

**Comment by glennmatthews** [comment]
No issue here! Sorry for the delay.

**Pull request merged**
