### PR TITLE
Add markdownlint

### PR DESCRIPTION
**Pull request by glennmatthews**
Closes: #1385 
# What's Changed

- Add `invoke markdownlint` task
- Expand scope of markdownlint (beyond what was previously tested in #1557) to include `examples` directory and `*.md` files in the project root.
- Run markdownlint and fix any new issues that it uncovers
- Delete `scripts/cibuild.sh` rather than updating it to include markdownlint, since it's not actually used anywhere now.

# TODO
- [x] Add to development Docker image (will do after #1620 is merged so as to avoid merge conflicts)
- [x] Add to CI (will do after #1628 is merged so as to avoid merge conflicts)

### CODE REVIEW

**Comment by bryanculver** [comment]
Waiting on the merge of #1628 before merging this PR.

**Comment by bryanculver** [comment]
Waiting on the merge of #1628 before merging this PR.

**Comment by glennmatthews** [comment]
Please don't merge this immediately after merging #1628 - I need to make code updates to this PR in its wake.

**Review by bryanculver — APPROVED** [review]
LGTM

**Pull request merged**
