### PR TITLE
Moved runjob helper functions from `__init__.py` to `utils.py`

### PR DESCRIPTION
**Pull request by HanlinMiao**

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]
Looks reasonable - have you been able to test it?

**Comment by HanlinMiao** [comment]
> Looks reasonable - have you been able to test it?

Sorry for my ignorance but how do you test this? I thought we can only merge this and redeploy the sandbox and see if anything blows up.

**Comment by glennmatthews** [comment]
> > Looks reasonable - have you been able to test it?
> 
> Sorry for my ignorance but how do you test this? I thought we can only merge this and redeploy the sandbox and see if anything blows up.

Should be sufficient to set up a new (no existing DB) instance of Nautobot with `nautobot-app-firewall-models` installed/enabled and confirm that it starts up, migrates, and runs successfully.

**Comment by HanlinMiao** [comment]
> > > Looks reasonable - have you been able to test it?
> > 
> > 
> > Sorry for my ignorance but how do you test this? I thought we can only merge this and redeploy the sandbox and see if anything blows up.
> 
> Should be sufficient to set up a new (no existing DB) instance of Nautobot with `nautobot-app-firewall-models` installed/enabled and confirm that it starts up, migrates, and runs successfully.

Tested and started up successfully👍

**Pull request merged**
