### PR TITLE
Zackt25 update readme gifs for 2.1

### PR DESCRIPTION
**Pull request by zackt25**
# Closes: #4897
# What's Changed

New Gif's for Nautobot 2.1 interface 

**Updated:** 
nautobot_config_context.gif
nautobot_golden_config.gif
nautobot_graphql.gif
nautobot_mainpage.gif
nautobot_prefix_hierarchy.gif

**Added:**
nautobot_modes.gif
nautobot_device_lifecycle_management.gif

### CODE REVIEW

**Review by timizuoebideri1 — APPROVED** [review]

**Review by glennmatthews — COMMENTED** [review]
New GIFs look great, though I see that the file sizes are all larger than before, such as `nautobot_golden_config` that's increased in size by a factor of 3. Since we're now only keeping these images in the Git repo, and not actually packaging them into the distributed package, this isn't necessarily a deal breaker, but is there anything that can/should be done to reduce these file sizes?

**Comment by zackt25** [comment]
I used the same quality as last time but I can bump it down no problem. I did extend some of them to include more  clicking and views then what was in the old gif.

**Comment by zackt25** [comment]
@glennmatthews I brought down most of the Gifs that were 5MB+ the only one I left was the mainpage at 7MB. Let me know if that is ok.

**Review by glennmatthews — APPROVED** [review]
Thank you!

**Pull request merged**
