### PR TITLE
[WIP] Add autofocus support to input forms

### PR DESCRIPTION
**Pull request by matt852**
# Closes: #1537 
# What's Changed

I've added the "autofocus" HTML attribute to all of the "Add X" input forms.  I did not add it to the CSV forms due to the way they are rendered.

I've checked each page individually and they autofocus properly, allow creating new objects properly, and any form field validation checks are working as well.

### CODE REVIEW

**Comment by matt852** [comment]
I moved this to the `next` branch instead of `develop`, and added support for the new "Add Dynamic Groups" form.

**Comment by glennmatthews** [comment]
I like the goal here but I'm not a huge fan of the implementation, as it becomes yet another thing that we have to remember to add manually when authoring a new form.  It seems to me like this should be something we should be able to achieve more automatically with a bit of appropriately clever JavaScript - see for example https://stackoverflow.com/questions/277544/how-do-i-set-the-focus-to-the-first-input-element-in-an-html-form-independent-fr (first result I found on Google, not necessarily endorsing any specific implementation)

**Comment by bryanculver** [comment]
> I like the goal here but I'm not a huge fan of the implementation, as it becomes yet another thing that we have to remember to add manually when authoring a new form. It seems to me like this should be something we should be able to achieve more automatically with a bit of appropriately clever JavaScript - see for example https://stackoverflow.com/questions/277544/how-do-i-set-the-focus-to-the-first-input-element-in-an-html-form-independent-fr (first result I found on Google, not necessarily endorsing any specific implementation)

Agreed. Ideally I would like to see this being done with a generator where it may set a default (the first) but allowing it to be overridden per form.

However as a stop-gap I think a feature like this can add some useful UX improvements without significant code bloat. Thoughts @lampwins?

**Comment by matt852** [comment]
I don't necessarily like using the first entry item in a form as set to autofocus.  Each form is different, with some of their first items being drop down lists.  We can't set the default `autofocus` to always be the Name field, as some forms either don't have it, or Name isn't the first text-entry item.

I will look into some kind of dynamic input idea using JQuery or similar in the meantime.

**Comment by bryanculver** [comment]
Closed. Tracking stale PRs in #2812.

**Pull request closed without merging**
