### PR TITLE
Removing old unused RQ_DEFAULT_TIMEOUT variable

### PR DESCRIPTION
**Pull request by nniehoff**
This PR Removes references to the old `RQ_DEFAULT_TIMEOUT` which is no longer being used.

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Thanks for the fix! 

I notice that the `RQ_QUEUES` section in `docs/configuration/required-settings.md` does not currently describe the purpose of the `DEFAULT_TIMEOUT` parameter - perhaps some of the wording that you've correctly removed from `optional-settings.md` should be added there?

**Comment by jathanism** [comment]
@nniehoff Glenn is referring to this section, https://nautobot.readthedocs.io/en/latest/configuration/required-settings/#rq_queues

If you wouldn't mind moving the mention of `DEFAULT_TIMEOUT` there with the text you ripped out of the optional-settings doc? Thank you!

**Comment by nniehoff** [comment]
Good catch, updated

**Review by glennmatthews — APPROVED** [review]
Looks good to me - thank you!

**Pull request merged**
