### PR TITLE
[WIP] CI Integration Testing Improvements

### PR DESCRIPTION
**Pull request by nniehoff**
As a result of #1173 we need to do more testing in docker.  Unfortunately, that slows things down a bit.  The purpose of this PR is ultimately test the production built containers.  Some things we are doing in this PR:

- [x] Create a workflow for CI on Pull Requests, this process should be similar to the existing one however based on a suggestion by @glennmatthews remove python 3.7 and 3.8 assume if 3.6 and 3.9 pass then we are good enough for a PR
- [ ] Create a workflow for push/merge to develop, next, or main this workflow should run all of the same tests, but this time execute these tests inside the built docker containers.  (Linting excluded still run that quickly outside of the containers)
- [ ] Merge workflows should test all supported python versions
- [ ] Run the unit tests in the -dev containers and run the integration tests in the prod container

Some current challenges:

- [ ] Integration tests currently rely in django to provide a test db and expose the app on a random port.  Running the tests from outside of the container causes issue.  Current ideas for solutions would be to either add selenium as a prod dependency or have a static testing DB and run the tests using selenium but not through django
- [ ] On merge should we run unit tests first or run unit tests + integration tests at the same time
- [ ] MySQL unittests are [currently failing inside docker containers](https://github.com/nautobot/nautobot/runs/4570741411?check_suite_focus=true#step:9:1216), this can be re-produced locally maybe @jathanism can take a look

Please note there are several TODOs in this PR for me to cleanup before submission.  Currently I am running the "ci - merge" process on a PR so it can be tested, this will need to change.

### CODE REVIEW

**Comment by nniehoff** [comment]
@jathanism I've done a bit more work on getting the integration tests working in the prod container.  So far I've had to force the port to 8080 to always hit the prod container, force the prod container to use the test db... Next I'm going to have to install the dummy plugin.  I'm wondering if we need to rethink running the integration tests in the prod containers... I really like the idea but we are going to have to work quite a bit of tweaks

**Comment by bryanculver** [comment]
@glennmatthews @nniehoff @jathanism I think most of these items have been addressed, correct?

Safe to close?

**Comment by jathanism** [comment]
> @glennmatthews @nniehoff @jathanism I think most of these items have been addressed, correct?
> 
> 
> 
> Safe to close?

I think so but let's let Nick make the final call since this is his baby monkey.

**Comment by nniehoff** [comment]
@bryanculver no, I don't think this has been resolved at all.  I was waiting for @jathanism to give the testing in MySQL containers a look but I'm sure he has forgotten.  This PR probably needs some love to catch up with the current baseline.

**Comment by bryanculver** [comment]
Closed. Tracking stale PRs in #2812.

We should move this to an entire epic around improving CI complete with user stories.

**Pull request closed without merging**
