### PR TITLE
Update 3-nautobot.md

### PR DESCRIPTION
**Pull request by htam-net**

### CODE REVIEW

**Comment by htam-net** [comment]
this pull request doesn't resolve issue 62 but is small contribution towards its resolution

**Comment by jathanism** [comment]
Thanks @htam-net for the contribution! I'm in the midst of revising the whole install doc right now in #74 so hopefully that will address your PR. Would love your feedback after it is wrapped up!

**Comment by htam-net** [comment]
OK. I will monitor for an update.

**Comment by jathanism** [comment]
@htam-net We've greatly overhauled the install docs to not even require activating the virtualenv and also patched Nautobot to be smarter about where to look for files. Can you please give v1.0.0b2 a shot?

I'll be closing this, but please follow up if you're having issues. Thanks!

**Pull request closed without merging**
