### PR TITLE
UI Detail Page Redesign

### PR DESCRIPTION
**Pull request by timizuoebideri1**
# Closes: #<ISSUE NUMBER GOES HERE>
# What's Changed

**UI**:
Screenshot 2023-05-08 at 2 54 27 PM

**SCHEMA**

```json
"detail_view_schema": {
        "column_no": 2,
        "columns": {
            "1": {
                "col": 1,
                "groups": {
                    "Device": {
                        "template": "list",
                        "template_actions": [],
                        "fields": [
                            {
                                "label": "Location",
                                "value": "Campus-07",
                                "link": {
                                    "app_label": "dcim",
                                    "model_name": "location",
                                    "id": "612373af-2624-4a7f-8f93-3aad4b891502"
                                },
                                "color": null
                            },
                            {
                                "label": "Rack",
                                "value": null,
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Position (U)",
                                "value": null,
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Tenant",
                                "value": "Mckee, Guzman and Nguyen",
                                "link": {
                                    "app_label": "tenancy",
                                    "model_name": "tenant",
                                    "id": "d3fa4f12-b650-4ced-8cd2-e20d4b403b1d"
                                },
                                "color": null
                            },
                            {
                                "label": "Device type",
                                "value": "Citrix Citrix DeviceType 5",
                                "link": {
                                    "app_label": "dcim",
                                    "model_name": "devicetype",
                                    "id": "1d331bfd-9dca-49f6-9cfe-27bfbea7ca45"
                                },
                                "color": null
                            },
                            {
                                "label": "Serial number",
                                "value": "",
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Asset tag",
                                "value": null,
                                "link": null,
                                "color": null
                            }
                        ]
                    },
                    "Management": {
                        "template": "list",
                        "template_actions": [],
                        "fields": [
                            {
                                "label": "Role",
                                "value": "SoftOdd",
                                "link": {
                                    "app_label": "extras",
                                    "model_name": "role",
                                    "id": "21c1baf9-014b-4320-abc2-4ecf3db7e3a4"
                                },
                                "color": "2f6a31"
                            },
                            {
                                "label": "Platform",
                                "value": "Fake Platform 23",
                                "link": {
                                    "app_label": "dcim",
                                    "model_name": "platform",
                                    "id": "c1e5b73c-abe3-45da-848c-73eaecaba81a"
                                },
                                "color": null
                            },
                            {
                                "label": "Status",
                                "value": "Active",
                                "link": {
                                    "app_label": "extras",
                                    "model_name": "status",
                                    "id": "4a8ca46c-ae32-4d9e-822a-2edd9fe3123b"
                                },
                                "color": "4caf50"
                            },
                            {
                                "label": "Primary IPv4",
                                "value": null,
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Primary IPv6",
                                "value": null,
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Secrets group",
                                "value": null,
                                "link": null,
                                "color": null
                            },
                            {
                                "label": "Device Redundancy Group",
                                "value": null,
                                "link": null,
                                "color": null
                            }
                        ]
                    },
                    "Comments": {
                        "template": "box_full",
                        "template_actions": [],
                        "field": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
                    }
                }
            },
            "2": {
                "col": 2,
                "groups": {
                    "Services": {
                        "template": "table",
                        "template_actions": [
                            "add"
                        ],
                        "table_data": null
                    }
                }
            }
        }
    }
```

**SERIALIZER CLASS**
```python
class DeviceSerializer(NautobotModelSerializer, TaggedModelSerializerMixin):
    face = ChoiceField(choices=DeviceFaceChoices, allow_blank=True, required=False)
    parent_bay = serializers.SerializerMethodField()

    class Meta:
        model = Device
        fields = "__all__"
        validators = []
        detail_view_schema = {
            "columns": 2,
            "grouping": {
                "Device": { 
                    "fields": ["location", "rack", "position", "tenant", "device_type", "serial", "asset_tag"],
                    "col": 1,
                    "template": "list"
                },
                "Management": { 
                    "fields": ["role", "platform", "status", "primary_ip4", "primary_ip6", "secrets_group", "device_redundancy_group"],
                    "col": 1,
                    "template": "list"
                },
                # Add Custom Fields, Tags Automatically
                "Comments": { 
                    "field": "comments",
                    "col": 1,
                    "template": "box_full"
                },
                "Services": { 
                    "table": {
                        "table_class": "TableClass",  # This class should be able to build the table schema
                        "actions": ["changelogs", "edit", "delete"],
                        "field": "services"
                    },
                    "col": 2,
                    "template": "table",
                    "template_actions": ["add"]
                },
                "Services": { 
                    "table": {
                        "table_class": "TableClass",  # This class should be able to build the table schema
                        "actions": ["changelogs", "edit", "delete"]
                    },
                    "col": 2,
                    "template": "table",
                    "template_actions": ["add"]
                },
            }
        }
```

Yet to be done:

- [ ] Fix Detail page broken; (Other Tabs apart from the main tab is not functioning)
- [ ] Box Template: e.g grouping for Tags, Comments and Notes
- [ ] Table Template: e.g Groupings for M2M fields that requires table like Services

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by bryanculver** [comment]
- This needs to be returned from the OPTIONS query against the detail endpoint
- Review this schema and pattern against alternative
- Commit to schema in next design meeting

**Comment by glennmatthews** [comment]
Please rebase under latest `next`, as it's not really reviewable in its current form due to merge issues and irrelevant code.

**Comment by glennmatthews** [comment]
Relates to #3526?

**Comment by glennmatthews** [comment]
Relates to #3528?

**Comment by bryanculver** [comment]
Replaced by #3816

**Pull request closed without merging**
