### PR TITLE
Rackview UI Add Option to Truncate to Host Portion of FQDN

### PR DESCRIPTION
**Pull request by jvanderaa**
# Closes: #1119 
# What's Changed

This change adds an option to only display the host portion of a device name (splitting on `.`). This option defaults to False since the existing behavior is to show the full hostname. 

To do this, I found where the str(device) was at, and added an if conditional of `str(device).split(".")[0] if settings.UI_VAR_NAME else str(device)`. I added it to two locations, one on the rack front rendering and then a second for the rear. These are different in how they are done, but the effect works.

The risk with this approach is on the full DCIM side of a rack. That is patch panel names have a `.` in them, then this will also split on that as well. Should we look at some opinionated names?

## Before Screenshot

Screen Shot 2022-04-30 at 11 47 09

## After Screenshot

Screen Shot 2022-04-30 at 11 49 33

## Remaining Work

From the TODO section, I will add documentation as well if the logic of this change works. I will also need to figure out where the unit tests are going to be added.

# TODO

- [x] Explanation of Change(s)
- [x] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [x] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by bryanculver** [comment]
@jvanderaa I'm on the fence of this being an environment setting.

Would it be possible to generate two text boxes, one FQDN and one with just the host name? Essentially rendering

```svg
#...
<text class="rack-fqdn-name">host.site.nautobot.com</text>
<text class="rack-host-name">host</text>
#...
```

Then a small bit of JavaScript could be written to toggle the view/hide states between these?

**Comment by martin-networker** [comment]
@jvanderaa

**Comment by martin-networker** [comment]
@jvanderaa Hello Josh.
This split solution expects a dot to be in device name. Could string slicing be used instead?
My suggestion is to use some parameter (e.g. UI_NAME_LNGT), which will be ideally set per user but even one shared/global value would do.
str(device)[:UI_NAME_LNGT] if settings.UI_NAME_LNGT > 0 and len(str(device)) > UI_NAME_LNGT else str(device)

**Comment by bryanculver** [comment]
> We can look to add in both settings. I think that just having string parsing wouldn't work out well. Many places I have been at have the device number towards the end. If the slice were at 7 chars and the given hostnames:
> 
> ```
> serverhost001
> serverhost002
> serverhost003
> ```
> 
> WIth those given hostnames, if the slice were even at 12 chars, there would be significant loss of information displayed with just a slicing.
> 
> @bryanculver from our design session, can we pass in string instead of boolean for the display setting?

🤷 Converting the displayed name between hostname and FQDN would be common practice considering the network domain. Splitting on any other arbitrary character or string length would be it's on paradigm.

Slicing is suboptimal for the example you give above @jvanderaa. There is no standard for string length conventions and formats.

I would say that string slicing is another feature itself, outside what is necessary to solve #1119.

However a `settings.py` setting could be established that defined a function to be used to trim the display name, something like:

```py
RACK_VIEW_SHORT_NAME_FILTER = lambda n : str(n).split(".")[0]
```

But this could be overridden by any administrator per installation. I would like to see that have it's own feature request where we can help identify the requirements said feature would need to be able to address.

**Comment by martin-networker** [comment]
@jvanderaa 
The point is we will be able to set the number of characters so if we will see that for example 12 characters is not enough we could increase it to 16 or something else.
Your case rely on having dot in device name which is not always the case and unfortunately one our team distinguish servers in the suffix. For example:
server123.ams.prod.company.com
server123.ams.stage.company.com
server123.fra.prod.company.com
server123.fra.stage.company.com

So instead of relying on having dot in all device names and in correct part of the name more unified solution seem to me to set specific number of characters.

**Comment by bryanculver** [comment]
Superseded by #1824

**Pull request closed without merging**
