### PR TITLE
Fixed template lookup logic in ObjectNotesView, ObjectDynamicGroupsVi…

### PR DESCRIPTION
**Pull request by HanlinMiao**
…ew and ObjectChangeLogView.

# Closes: #2509 
# What's Changed

# TODO

- [ ] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Change looks reasonable, but would it make sense to create a common helper function or base class that these three views could share so as to not need code in triplicate?

**Review by bryanculver — APPROVED** [review]
@HanlinMiao Just to confirm, is the issue that plugins are trying to use the new template naming convention even though it was most heavily used in `NautobotUIViewSet`?

**Comment by HanlinMiao** [comment]
> @HanlinMiao Just to confirm, is the issue that plugins are trying to use the new template naming convention even though it was most heavily used in `NautobotUIViewSet`?

Yeah, the new plugins are trying to follow the new naming conventions but we have to incoporate both template lookup logic so as not to break some of the existing plugins.

**Comment by bryanculver** [comment]
> 

👍 I know we added backwards compatibility templates our side to address this fact but good to know.

**Pull request merged**
