### PR TITLE
Fixed upstream testing workflow

### PR DESCRIPTION
**Pull request by gsnider2195**
# Closes #DNE
# What's Changed

Fix upstream testing workflows showing successful when one of the steps fail

# Screenshots

## Before

https://github.com/nautobot/nautobot-app-ssot/actions/runs/8610217927

image

## After

https://github.com/gsnider2195/nautobot-app-ssot-gha-test/actions/runs/8724938540

image

https://github.com/gsnider2195/nautobot-app-ssot-gha-test/actions/runs/8725146406

image

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example App Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by gsnider2195** [comment]
@bryanculver do you see any issues with this? You're the expert on this workflow 😄 

For reference: https://www.edwardthomson.com/blog/github_actions_6_fail_fast_matrix_workflows.html

**Comment by glennmatthews** [comment]
A concern as I understand it was whether failures in repo A would cause runs in-progress in repo B to be auto-cancelled instead of running to completion. Have you been able to test that behavior?

**Comment by gsnider2195** [comment]
> A concern as I understand it was whether failures in repo A would cause runs in-progress in repo B to be auto-cancelled instead of running to completion. Have you been able to test that behavior?

I'm not seeing anywhere in our upstream testing where we could affect the workflows of another repository

**Comment by bryanculver** [comment]
The only side-effect I can forsee (which may have arisen from testing) is that any task trying to be run after the matrix (either here or in the use of this, see: https://github.com/nautobot/nautobot-app-ssot/blob/479d77feb1ca75216f1ab41611d4211778e3e3bc/.github/workflows/upstream_testing.yml#L8-L13) would not be allowed to run.

But my memory is fuzzy on what or why this was put in so 🤷. If it wasn't documented it must not be important.

**Comment by gsnider2195** [comment]
> The only side-effect I can forsee (which may have arisen from testing) is that any task trying to be run after the matrix (either here or in the use of this, see: https://github.com/nautobot/nautobot-app-ssot/blob/479d77feb1ca75216f1ab41611d4211778e3e3bc/.github/workflows/upstream_testing.yml#L8-L13) would not be allowed to run.
> 
> But my memory is fuzzy on what or why this was put in so 🤷. If it wasn't documented it must not be important.

Do we know of any apps that are extending this workflow to run any additional steps?

**Comment by bryanculver** [comment]
> > The only side-effect I can forsee (which may have arisen from testing) is that any task trying to be run after the matrix (either here or in the use of this, see: https://github.com/nautobot/nautobot-app-ssot/blob/479d77feb1ca75216f1ab41611d4211778e3e3bc/.github/workflows/upstream_testing.yml#L8-L13) would not be allowed to run.
> > But my memory is fuzzy on what or why this was put in so 🤷. If it wasn't documented it must not be important.
> 
> Do we know of any apps that are extending this workflow to run any additional steps?

Not that I know of. Could have been something that came up somewhere in this lifecycle:
- https://github.com/nautobot/nautobot/pull/2377
- https://github.com/nautobot/nautobot-plugin-netutils/pull/2

But YAGNI probably at this point.

**Review by HanlinMiao — APPROVED** [review]

**Comment by gsnider2195** [comment]
I happened to have a PyGithub script laying around from some research I was doing on the upstream testing workflows earlier this week so I iterated through every github actions workflow with "upstream" in the name and checked the files. The only file that didn't match was https://github.com/nautobot/nautobot-plugin-ssot-servicenow/blob/develop/.github/workflows/upstream_testing.yml and that was just whitespace differences.

**Pull request merged**
