### PR TITLE
Add docu.: VScode Debugging Inside Container

### PR DESCRIPTION
**Pull request by jifox**
Update documentation: How to debug the nautobot-server inside the docker container with Visual Studio Code.
   
Feel free to modify as you like. I'm not a native speaker.

Thx for making this great project open source

Josef

### CODE REVIEW

**Comment by glennmatthews** [comment]
Thank you for the pull request! We're looking at updating the current VSCode integration as part of fixing #51, so this change set may end up being combined into a larger set of changes soon.

**Comment by glennmatthews** [comment]
Hi Josef, sorry for the trouble, but it looks like something's gotten lost in your merge updates - while GitHub is now showing a set of diffs for this PR, they're all changes that are already present in our `develop` branch. When I check out your fork locally it's now showing no diffs at all against `develop`. Now that #73 is merged, do you find that there are still documentation updates you'd like to make? If so, you might need to re-add your changes to a new branch and open a new pull request. Apologies again for the inconvenience!

**Comment by jifox** [comment]
hi @glennmatthews 

Sorry for the inconvenience too. I have filed a new Pull request #108 that takes into account the new changes.

**Comment by glennmatthews** [comment]
Thank you! Closing this in favor of #108.

**Pull request closed without merging**
