### PR TITLE
Correct Power Feed and Power Panel Navigation

### PR DESCRIPTION
**Pull request by smk4664**
### Fixes: #759 

Correct the button actions for Power Feed and Power Panel in the Nav Bar.

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Thanks for the pull request! Comparing to https://github.com/nautobot/nautobot/pull/737/files#diff-ab949fb1e4b92187f41616d6dbb38f5706d3da797f8d99e238bec86d89db0b12, I'd like to see it match that change, i.e. defining the `Add` button first and the `Import` button second -- the actual ordering in the code doesn't matter *per se* because `NavMenuImportButton` and `NavMenuAddButton` have appropriate default `weight` values, but this would make these items consistent with other menus/apps and reduce potential for confusion.

**Comment by smk4664** [comment]
Sure! I can make this swap.

**Comment by glennmatthews** [comment]
Thanks for the update! Need to make the same change under `powerpanel_list`, I believe.

**Comment by smk4664** [comment]
> Thanks for the update! Need to make the same change under `powerpanel_list`, I believe.

Got it this time.  I was trying to do too much at once.

**Review by glennmatthews — APPROVED** [review]
Thanks!

**Review by jathanism — APPROVED** [review]
I had found and fixed this in my feature branch for templates, so I'm glad you caught it, too.

**Pull request merged**
