### PR TITLE
Updating jsonschema for python >= 3.7

### PR DESCRIPTION
**Pull request by nniehoff**
# What's Changed

Updating jsonschema dependency for newer versions of Python

# TODO

- [x] Explanation of Change(s)
- [x] Attached Screenshots, Payload Example
- [x] Unit, Integration Tests
- [x] Documentation Updates (when adding/changing features)
- [x] Example Plugin Updates (when adding/changing features)
- [x] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by bryanculver** [comment]
@nniehoff What's the reason this needs to go in? Seeing as 1.3 is on the horizon I'm curious why the bump to 4.4.X

Reason I ask is using split dependencies for anything but addressing vulnerabilities is a bit of a quagmire.

**Comment by glennmatthews** [comment]
Agreed - unless this is critically required in 1.2, let's make this change in `next` instead where we no longer need to maintain a split dependency for Python 3.6.

**Comment by nniehoff** [comment]
We have some private plugins that have third-party dependencies on the bump to 4.x

**Comment by bryanculver** [comment]
Plugins should use the dependencies compatible with Nautobot, which is why adding `nautobot` as a package dependency is idea. You will get compatible versions for free essentially.

1.3 will bump `jsonschema` to 4.4.X.

**Pull request closed without merging**
