### PR TITLE
Fix last login time being updated during maintenance mode with remote user authentication

### PR DESCRIPTION
**Pull request by joaopsys**
# Closes: #2477 
# What's Changed

- Added a missing check for `MAINTENANCE_MODE` during remote user authentication similarly to how it is done in [users/views.py](https://github.com/nautobot/nautobot/blob/21c85f25e6458ad97e62484bc89e5effa1328a80/nautobot/users/views.py)
  - Last login time for remotely authenticated users was still being updated during maintenance mode, which would fail if the underlying database was read-only

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [x] Documentation Updates (when adding/changing features)
- [x] Example Plugin Updates (when adding/changing features)
- [x] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Thanks for the PR! I get the fix here but it feels like there should be a more elegant way of doing this - do we really need to re-disconnect the signal on every processed request, or is this something we could be doing once globally, perhaps in `settings.py`?

**Comment by joaopsys** [comment]
You got me @glennmatthews, I can't say I know what I'm doing here when it comes to Django 😁 

I will try to find some time to make it more elegant

**Comment by joaopsys** [comment]
@glennmatthews I will not have time to work on this unfortunately. Feel free to close the PR if nobody else can chip-in!

**Comment by bryanculver** [comment]
> Thanks for the PR! I get the fix here but it feels like there should be a more elegant way of doing this - do we really need to re-disconnect the signal on every processed request, or is this something we could be doing once globally, perhaps in `settings.py`?

@glennmatthews This happens in `django.contrib.auth` app loading: https://github.com/django/django/blob/3.2.16/django/contrib/auth/apps.py#L27

So maybe in the `NautobotConfig` app ready signal we could fire this then?

@joaopsys' implementation cribs off the other other `LoginView` implementation but because RemoteAuth happens (revalidating) on every request it's why it's here. Potentially moving it to the Core app ready signal could solve both.

Thoughts @jathanism?

**Comment by joaopsys** [comment]
Thanks for the tips @glennmatthews and @bryanculver

I'm trying to understand and learn how this all fits together, but for now I've added the following to `core/apps/__init__.py` under the `CoreConfig` class' `ready` function:

```
        from django.conf import settings
        from django.contrib.auth.signals import user_logged_in
        from django.contrib.auth.models import update_last_login

        # If maintenance mode is enabled, assume the database is read-only, and disable updating the user's
        # last_login time upon authentication.
        if settings.MAINTENANCE_MODE:
            user_logged_in.disconnect(update_last_login, dispatch_uid="update_last_login")

        post_migrate.connect(post_migrate_send_nautobot_database_ready, sender=self)
```

It seems to work on my end. Is this the solution you were referring to?

**Comment by bryanculver** [comment]
> Thanks for the tips @glennmatthews and @bryanculver
> 
> I'm trying to understand and learn how this all fits together from your comments, so for now I've added the following to `core/apps/__init__.py` under the `CoreConfig` class' `ready` function:
> 
> ```
> class CoreConfig(NautobotConfig):
>     """
>     AppConfig for the core of Nautobot.
>     """
> 
>     name = "nautobot.core"
>     verbose_name = "Nautobot Core"
> 
>     def ready(self):
>         from graphene_django.converter import convert_django_field
>         from nautobot.core.graphql import BigInteger
> 
>         @convert_django_field.register(JSONField)
>         def convert_json(field, registry=None):  # pylint: disable=redefined-outer-name
>             """Convert JSONField to GenericScalar."""
>             return generic.GenericScalar()
> 
>         @convert_django_field.register(BinaryField)
>         def convert_binary(field, registry=None):  # pylint: disable=redefined-outer-name
>             """Convert BinaryField to String."""
>             return String()
> 
>         @convert_django_field.register(BigIntegerField)
>         def convert_biginteger(field, registry=None):  # pylint: disable=redefined-outer-name
>             """Convert BigIntegerField to BigInteger scalar."""
>             return BigInteger()
> 
>         from django.conf import settings
>         from django.contrib.auth.signals import user_logged_in
>         from django.contrib.auth.models import update_last_login
> 
>         # If maintenance mode is enabled, assume the database is read-only, and disable updating the user's
>         # last_login time upon authentication.
>         if settings.MAINTENANCE_MODE:
>             user_logged_in.disconnect(update_last_login, dispatch_uid="update_last_login")
> 
>         post_migrate.connect(post_migrate_send_nautobot_database_ready, sender=self)
> 
>         super().ready()
> 
>         ...
> ```
> 
> It seems to work on my end. Is this the solution you were referring to?

That's awesome that that works! Yes that would be the thought and we could remove it from `LoginView` as well.

@glennmatthews: `UsersConfig` has no ready signal overloading as it stands and starts a bit later in the app chain. Is it OK to keep these connections/disconnections in the Core ready signal?

@joaopsys: Could you try moving the imports to the top? Those imports should cause any circular issues since they should have already been brought in and ready from earlier apps.

**Comment by joaopsys** [comment]
@bryanculver do you mean moving the imports to the top of the file or the `ready` function?

Moving it to the top of the file throws the following errors, so I assume you mean the function?

```
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: Traceback (most recent call last):
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/bin/nautobot-server", line 5, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.core.cli import main
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/cli.py", line 13, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.extras.plugins.utils import load_plugins
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/extras/plugins/__init__.py", line 12, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.core.apps import (
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/apps/__init__.py", line 9, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from django.contrib.auth.models import update_last_login
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: class AbstractBaseUser(models.Model):
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/base.py", line 108, in __new__
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: app_config = apps.get_containing_app_config(module)
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: self.check_apps_ready()
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: settings.INSTALLED_APPS
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: self._setup(name)
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: raise ImproperlyConfigured(
Nov 23 08:08:05 nautobot-server nautobot-server[14353]: django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by bryanculver** [comment]
> @bryanculver do you mean moving the imports to the top of the file or the `ready` function?
> 
> Moving it to the top of the file throws the following errors, so I assume you mean the function?
> 
> ```
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: Traceback (most recent call last):
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/bin/nautobot-server", line 5, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.core.cli import main
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/cli.py", line 13, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.extras.plugins.utils import load_plugins
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/extras/plugins/__init__.py", line 12, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from nautobot.core.apps import (
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/nautobot/core/apps/__init__.py", line 9, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from django.contrib.auth.models import update_last_login
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: class AbstractBaseUser(models.Model):
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/db/models/base.py", line 108, in __new__
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: app_config = apps.get_containing_app_config(module)
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: self.check_apps_ready()
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: settings.INSTALLED_APPS
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: self._setup(name)
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: File "/opt/nautobot/lib64/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: raise ImproperlyConfigured(
> Nov 23 08:08:05 nautobot-server nautobot-server[14353]: django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
> ```

Interesting... Well then I think it's sufficient to update the PR to what you shared in the comment above.

**Comment by joaopsys** [comment]
@bryanculver done.

I did not touch the disconnect that already exists in the LoginView since I don't want to risk breaking anything else.

**Review by bryanculver — APPROVED** [review]

**Pull request merged**
