### PR TITLE
Fix circular import introduced by #322.

### PR DESCRIPTION
**Pull request by jathanism**
### Fixes: #343 

This is cannot reproduced with unit tests. The unit tests did not catch this issue. This adds a `InterfaceConnectionsListView .get_queryset()` method to emulate the built-in Django generic view API that is unfortunately not implemented in the Nautobot core that we inherited from NetBox. So this also adds an `__init__` method to the view to call `self.get_queryset()` on init. Short of refactoring all of the base generic views, this is the cleanest fix I could think of for now. 

I did attempt to convert `InterfaceConnectionsListView.queryset` to a property, and while that did alleviate the issue initially, it resulted in many tests failing because [`nautobot.utilities.views.ObjectPermissionRequiredMixin.has_permission` wants to replace `self.queryset` with `self.queryset.restrict(user, action)` on line 77](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/views.py#L77).

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]
Fix looks good, but it's very concerning that #343 wasn't caught by or reproducible by the CI tests. From the issue description it sounds like it should be caught quite easily. Do you have any analysis why the tests aren't encountering it?

**Comment by glennmatthews** [comment]
Do we just need to add an `invoke migrate` to `scripts/cibuild.sh`?

**Comment by FragmentedPacket** [comment]
@glennmatthews I just tested and it appears that would have caught the issue. Would that be a simple enough addition like you said to `scripts/cibuild.sh`?

**Comment by jvanderaa** [comment]
I believe @nniehoff has something already in the works that would catch this.

**Comment by jathanism** [comment]
> Do we just need to add an `invoke migrate` to `scripts/cibuild.sh`?

`showmigrations` would be better because it still tries to build the dependencies to inspect the schema, without actually trying to apply them.

**Comment by jathanism** [comment]
> Fix looks good, but it's very concerning that #343 wasn't caught by or reproducible by the CI tests. From the issue description it sounds like it should be caught quite easily. Do you have any analysis why the tests aren't encountering it?

I am still looking into it, but my educated guess is that the test runner uses the same mechanism to apply the migrations to the test database that the migration operations code uses: Constructing the models in memory vs. reading them directly from the source.

**Pull request merged**
