### PR TITLE
Exclude docs source and animated gifs from built package

### PR DESCRIPTION
**Pull request by glennmatthews**
# Closes: #N/A
# What's Changed

- Update mkdocs to version 1.5.3 (needed because v1.5 adds support for the `exclude_docs` parameter)
- Update `mkdocs.yml` to exclude the `media/*.gif` files from the built docs (as the rendered docs don't actually reference these files, only `README.md` does, and they're quite large files)
- Update `mkdocs.yml` with recommended strict `validation` options added in mkdocs 1.5
- Update `pyproject.toml` to not package `CONTRIBUTING.md`, `CHANGELOG.md`, `NOTICE` files in the built package (since these aren't in the `nautobot/` directory, they end up in the `site-packages` root directory as clutter when pip installing nautobot from the package)
- Update `pyproject.toml` to not package `nautobot/docs/**/*` in the built package since it's redundant with the built documentation and resulted in a duplicate copy of every documentation image in the built package.

**Net-net here is to reduce the sdist and wheel files built for Nautobot from 85/86 MB in size down to a mere 30/31 MB.**

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- n/a Attached Screenshots, Payload Example
- n/a Unit, Integration Tests
- [x] Documentation Updates (when adding/changing features)
- n/a Example Plugin Updates (when adding/changing features)
- [x] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by glennmatthews** [comment]
Will need double-commit to ltm/1.6 as well.

**Comment by gsnider2195** [comment]
Since we're on mkdocs v1.5 now we can suppress this warning message using the [`not_in_nav`](https://www.mkdocs.org/user-guide/configuration/#not_in_nav) config:

```
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - models/examplemodel.md
```

Not sure if you want to include it in this PR, it's just something I noticed when looking at the docs.

**Comment by gsnider2195** [comment]
I'm seeing this warning now when building docs:

```
INFO    -  DeprecationWarning: A plugin has set File.page to an instance of Page and it got overwritten. The behavior of this will change in MkDocs 1.6.
             File "/usr/local/lib/python3.8/site-packages/mkdocs/structure/nav.py", line 183, in <listcomp>
               _data_to_navigation((key, value), files, config)
             File "/usr/local/lib/python3.8/site-packages/mkdocs/structure/nav.py", line 209, in _data_to_navigation
               warnings.warn(
```

It's not an issue yet, but we may get questions about it.

**Comment by glennmatthews** [comment]
Yes, I noticed that too. I wish it was clearer about *which* plugin is doing that :-)

I'll dig into it and see if I can find out where it's coming from and if an update is already available.

**Comment by gsnider2195** [comment]
> Yes, I noticed that too. I wish it was clearer about _which_ plugin is doing that :-)
> 
> I'll dig into it and see if I can find out where it's coming from and if an update is already available.

I did a grep through the `mkdocs*` plugins and couldn't find anything :(

**Comment by glennmatthews** [comment]
The interesting thing is that it looks like in the development branch for mkdocs 1.6 they've just removed that warning altogether - so it may be that there's not actually any action required in this case?

**Review by HanlinMiao — APPROVED** [review]

**Pull request merged**
