### PR TITLE
[WIP] validated create functions

### PR DESCRIPTION
**Pull request by whitej6**
Creating a set of validated create functions that invoke validated_save() vs save().

### CODE REVIEW

**Comment by whitej6** [comment]
@lampwins Is this something we would want to provide or is the tech debt of managing greater than the benefit?

**Comment by Kircheneer** [comment]
To give a bit of additional input, we are using a similar, self-baked pattern in multiple places, so from that perspective it would be great to have native support for this.

**Comment by lampwins** [comment]
@whitej6 yes I do think this is something useful for us. When we get into documentation it will be important to clearly define when using each method would be most appropriate.

**Comment by bryanculver** [comment]
Closed. Tracking stale PRs in #2812.

**Pull request closed without merging**
