### PR TITLE
Fixed export import inconsistency

### PR DESCRIPTION
**Pull request by timizuoebideri1**
# Closes: #1407 
# What's Changed

- Replace `self.get_status_display()` with `self.status.slug` in `to_csv()` method because import requires Status slug not value

# TODO

- [ ] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
Isn't changing the status rendering from `name` to `slug` considered a breaking change in the export? It also seems inconsistent to me given that we're using the `name` for most other related objects (provider.name, type.name, tenant.name, etc.) - why should `status` alone use a slug?

I know we'd decided on #1407 that changing the custom-field rendering was an acceptable fix given that the existing behavior is "wrong", but I don't recall what we'd discussed about statuses.

**Comment by timizuoebideri1** [comment]
> Isn't changing the status rendering from `name` to `slug` considered a breaking change in the export? It also seems inconsistent to me given that we're using the `name` for most other related objects (provider.name, type.name, tenant.name, etc.) - why should `status` alone use a slug?
> 
> I know we'd decided on #1407 that changing the custom-field rendering was an acceptable fix given that the existing behavior is "wrong", but I don't recall what we'd discussed about statuses.

I don't think it was discussed, but it was reported in the issue.
As to why I decided to change to slug, we have a lot of test cases that use a `status` `slug` in bulk import and IMO most people use a `status` `slug` while bulk importing.

**Comment by timizuoebideri1** [comment]
> Isn't changing the status rendering from `name` to `slug` considered a breaking change in the export? It also seems inconsistent to me given that we're using the `name` for most other related objects (provider.name, type.name, tenant.name, etc.) - why should `status` alone use a slug?
> 
> I know we'd decided on #1407 that changing the custom-field rendering was an acceptable fix given that the existing behavior is "wrong", but I don't recall what we'd discussed about statuses.

True it was not discussed.
Changes made to status have been reverted

**Comment by martin-networker** [comment]
Will following export/import inconsistencies be solved within this issue?
    field "rack_number" in export has to be "rack" in import
    field "rack_face" in export has to be "face" in import
    field "rack_face" has value "Front" in export but in import it has to be "front"

**Pull request merged**
