### PR TITLE
add support for python 3.10

### PR DESCRIPTION
**Pull request by alextremblay**
### Fixes: #1167

This change adds python 3.10 to the test matrix and container build matrix, and bumps `psycopg2-binary` to a version which supports python 3.10

All other dependencies appear to already support python 3.10, psycopg was the only dep that needed to be updated in order for all the tests to pass, and the containers to build succesfully:

https://github.com/utsc-networking/nautobot/actions/runs/1678123195

### CODE REVIEW

**Comment by glennmatthews** [comment]
Thanks for the pull request! This is probably a change that should be made in `next` (i.e. Nautobot 1.3.0) instead of `develop` (Nautobot 1.2.x), as we're also planning to drop support for Python 3.6 in 1.3.0. Would you mind retargeting your PR to `next`? 

For completeness, I think the following files also need to be modified:

- `.github/workflows/release.yml`, add 3.10 so that we start building Docker images for 3.10 as well
- `nautobot/docs/index.md`, line 66, note that 3.10 is supported
- `nautobot/docs/docker.md`, line 52, note that 3.10 is built and published
- `nautobot/docs/development/release-checklist.md`, include 3.10 in the manual Docker build/publish steps.

**Comment by bryanculver** [comment]
Thanks for updating this @alextremblay!

We are looking to get this into `next` soon. If you could address the conflict we can merge this. 😄

**Comment by alextremblay** [comment]
excellent!

I've fixed the merge conflict, i think. (This is my first time taclking a merge confolict, so if I did it wrong please let me know :)

**Review by glennmatthews — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
