### PR TITLE
Update the home link in Nautobot 2.0 UI

### PR DESCRIPTION
**Pull request by DistantVoyager**
# Closes: #3953 <ISSUE NUMBER GOES HERE>
# What's Changed

- Added HomeIcon from `nautobot-ui` and linked to "/".
- Removed static "Home" text.
- Fixed padding to be consistent.

### New:

image

image

### Before:

image

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [x] Attached Screenshots, Payload Example

### CODE REVIEW

**Review by jathanism — APPROVED** [review]
I'm a fan. There was some talk about breadcrumbs and home being there as this home button is not in the mockup for the design, but given we don't address this I think this update is sane.

**Comment by bryanculver** [comment]
@lampwins Can you provide your 2️⃣🪙 here?

**Comment by glennmatthews** [comment]
The `Home` text in the current UI is *supposed* to be breadcrumbs to the current view, e.g.:

image

but looks like that got broken along the way. I think I have a local fix for it, will open an alternative PR soon.

**Comment by lampwins** [comment]
@DistantVoyager I know we had the small "Home" text before, but what is your feeling on needing a home link at all? From my perspective it seems to be standard to just click on the site icon to go to the home page? My concern is simply in taking up space in the context/search bar, knowing more content will be present up there when apps start integrating.

**Comment by lampwins** [comment]
I just don't think it is necessary. Plus, I'd worry about the spacing with branded logos there. Let's not do this for now.

**Comment by bryanculver** [comment]
Combination of #3998 and just developing new habits, logo is sufficient for "Go To Home"

**Pull request closed without merging**
