### PR TITLE
Add obj check with settings.DOCS_ROOT

### PR DESCRIPTION
**Pull request by timizuoebideri1**
# Closes: #1539 
# What's Changed
Show help(?) icon `{% if obj and settings.DOCS_ROOT %}`

# TODO

- [x] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]

**Review by bryanculver — CHANGES_REQUESTED** [review]
This is targeting `develop` and will probably need to be rebased here in a few.

**Comment by glennmatthews** [comment]
This will collide with #1601, for what it's worth.

**Comment by bryanculver** [comment]
@glennmatthews @timizuoebideri1 Do we feel this sufficiently closes #1539?

The expected behavior as reported is that the user still can access help docs from the bulk view.

**Comment by bryanculver** [comment]
> I think we can close this without merging and revisit whether anything's needed after #1601 to address the bulk-edit view specifically.

#1601 is targeting `next`. Are we OK with this bug hanging around until then?

**Comment by glennmatthews** [comment]
We should discuss whether it would make sense to retarget #1601 to develop - IMHO it would be useful to have in before 1.4.

**Comment by bryanculver** [comment]
A feature cures a bug. No longer necessary due to #1601.

**Pull request closed without merging**
