### PR TITLE
[WIP] Best Practice Linter

### PR DESCRIPTION
**Pull request by Kircheneer**
# Closes: #2257
# What's Changed

*Note: This was originally not using pylint, I have force pushed over the old, manual approach.*

A couple of custom pylint rules have been added:
- Check if classes that inherit from certain base classes (e.g. `django_filters.BaseFilterSet`) also inherit from the respective Nautobot version (i.e. `nautobot.utilities.filters.BaseFilterSet`)
- Check that `instance.pk` is not used as an if condition

Current example output:
```
************* Module nautobot.tenancy.forms
nautobot/tenancy/forms.py:115:0: W5001: Uses correct base classes. (incorrect-base-class)
nautobot/tenancy/forms.py:129:0: W5001: Uses correct base classes. (incorrect-base-class)
************* Module nautobot.tenancy.filters
nautobot/tenancy/filters/__init__.py:78:0: W5001: Uses correct base classes. (incorrect-base-class)
```

# TODO
- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
flipping epic man!!

**Comment by itdependsnetworks** [comment]
I think would be great to partner with you on converting this to a pylint package. I think that once we setup a pattern, it shouldn't be too bad to build out. This would make is simple for plugins to implement as well.

**Comment by Kircheneer** [comment]
@itdependsnetworks one thing I'm wondering is whether I can use inspection like this in pylint, from what I can tell they lint based on the AST/raw source code rather then the already interpreted objects: https://pylint.pycqa.org/en/latest/development_guide/how_tos/custom_checkers.html

We need to have interpreted objects as for example we have to inspect the whole class hierarchy for these checks to make sense.

Do you have any experience there?

**Comment by Kircheneer** [comment]
New draft utilizing pylint this time. Check [pylint CI output](https://github.com/nautobot/nautobot/actions/runs/4606499834/jobs/8139982799?pr=2801) for details on what this currently reports.

**Pull request closed without merging**
