### PR TITLE
Fix crash when sorting by network address in UI

### PR DESCRIPTION
**Pull request by jathanism**
### Fixes: #278 

This applies to `Aggregate.prefix`, `Prefix.prefix`, and `IPAddress.address`.

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
Doesn't look like this can be tested at this point?

**Review by FragmentedPacket — APPROVED** [review]

**Comment by glennmatthews** [comment]
Are there similar issues with the IP Address columns (primary_ip, primary_ip4, primary_ip6) in the Devices table?

**Comment by jathanism** [comment]
> Are there similar issues with the IP Address columns (primary_ip, primary_ip4, primary_ip6) in the Devices table?

Just checked and they are fine since that column already uses an `order_by=("primary_ip6", "primary_ip4")` and because those are related fields (not computed fields) it works as expected.

**Comment by jathanism** [comment]
> Doesn't look like this can be tested at this point?

Just manual testing for now by clicking the column a couple times for each view.

**Review by glennmatthews — APPROVED** [review]
It bugs me that we're using `text-nowrap` on one of these three columns but not the other two, but that's not what you're here to fix. :-) Looks good, thanks!

**Comment by jathanism** [comment]
> It bugs me that we're using `text-nowrap` on one of these three columns but not the other two, but that's not what you're here to fix. :-) Looks good, thanks!

File a bug!

**Pull request merged**
