### PR TITLE
Bump netutils version

### PR DESCRIPTION
**Pull request by jlixfeld**
# Closes: #3144 
# What's Changed

Bump netutils to 1.4.0

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by bryanculver** [comment]
Thanks, @jlixfeld! Neither the original issue nor this describes why to upgrade to `netutils` 1.4. Is there a feature you're looking to take advantage of?

**Review by bryanculver — CHANGES_REQUESTED** [review]
Poetry lockfile need updating.

Please follow: https://docs.nautobot.com/projects/core/en/stable/development/getting-started/#install-poetry and run `poetry add netutils="~1.4.0"` to generate the lockfile updates.

**Comment by bryanculver** [comment]
Please add a changelog fragment (see: https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments)

Also to note: On your fork you should still use branches because now your `develop` is out of sync with our upstream which will cause rebase conflicts for your next PR. Also it inherits our branch protections which means I could not push a commit to your fork to add this fragment.

**Comment by jlixfeld** [comment]
Done.  Sorry for the hassle, and also apologies for the silly `Created 3144.changed` commit title.

**Review by bryanculver — APPROVED** [review]

**Pull request merged**
