### PR TITLE
Closing #2209

### PR DESCRIPTION
**Pull request by HanlinMiao**
It seems like..., graphiql.html has theme.js included in inc/javascript.html.

### CODE REVIEW

**Comment by HanlinMiao** [comment]
Was the `disable="disable"` got left on there by accident? @matt852

**Comment by matt852** [comment]
The `disable="disable"` is intentional and should be left there.  The javascript in `project-static/js/theme.js` updates this element accordingly.

This was working when the PR was submitted, but in looking at the HTML layouts, it looks like some of the `include` elements were rearranged a bit, so maybe it has to do with the import ordering?  I need to load this up locally to debug why this is happening.

**Comment by HanlinMiao** [comment]
It seems like we forgot to include the `modals/modal.html` in `graphiql.html` @matt852

**Comment by matt852** [comment]
Yeah that would do it!  Is it rendering correctly now locally?

**Comment by HanlinMiao** [comment]
Yeah it is rendering correctly locally now.

**Review by matt852 — APPROVED** [review]
LGTM

**Comment by HanlinMiao** [comment]
Screen Shot 2022-08-17 at 3 08 39 PM
New commit adds footer to graphql page and the retains footer's functionalities

**Review by glennmatthews — APPROVED** [review]

**Pull request merged**
