### PR TITLE
[WIP] Patch webhook and jobhook triggered multiple times for single change

### PR DESCRIPTION
**Pull request by MeganerdDev**
# Closes: #3015
# What's Changed

This change patches the multiple firings of a jobhook/webhook that occurs when there is a singular change in Nautobot
- Moves enqueue_job_hooks call from ./extras/signals.py to ./core/middleware.py

# Screenshots
image
image

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [x] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

**Comment by MeganerdDev** [comment]
- I have tested this to be working on Nautobot v1.5.23b1
- I was assisted on identifying this change, contribution credit to @gsnider2195 !

**Comment by MeganerdDev** [comment]
- Tested on both jobhooks and webhooks

**Comment by MeganerdDev** [comment]
- Ran black code formatter
- Removed unused import in ./extras/signals.py _handle_changed_object per flake8

**Review by glennmatthews — COMMENTED** [review]
From the test failures it looks like there's an issue on object deletion.

**Comment by MeganerdDev** [comment]
Also thanks @HanlinMiao !

**Comment by gsnider2195** [comment]
> * Tested on both jobhooks and webhooks

Wouldn't the `enqueue_webhooks` call also need to be moved out of the change logging code into the middleware?

**Review by glennmatthews — COMMENTED** [review]
So on reflection I'm not sure this approach works - you've made it so that a jobhook **only** triggers in response to a web UI request, instead of triggering on any change to an object. That's why the unit tests are failing - the test is using the `web_request_context` context manager around an ORM change, rather than going through the web UI, and is expecting a jobhook to be triggered in response, but it isn't.

**Comment by gsnider2195** [comment]
> So on reflection I'm not sure this approach works - you've made it so that a jobhook **only** triggers in response to a web UI request, instead of triggering on any change to an object. That's why the unit tests are failing - the test is using the `web_request_context` context manager around an ORM change, rather than going through the web UI, and is expecting a jobhook to be triggered in response, but it isn't.

Maybe we should also add it into the `web_request_context` context manager? Would that cover all supported use cases for change logging (UI, REST, ORM with `web_request_context`)?

**Comment by gsnider2195** [comment]
I propose we move this logic out of the middleware and into the `web_request_context` and change the middleware to use `web_request_context` instead of going directly to the `change_logging` context.

**Comment by gsnider2195** [comment]
I tried moving this over to the context manager but now I'm having problems with django not releasing the database connections. I tried moving the database access to a separate method that's called with `transaction.on_commit` and as a signal that gets fired but neither of these fixes the issue.

https://github.com/nautobot/nautobot/compare/ltm-1.6...u/gas-3015-webhook-jobhook?expand=1

**Comment by gsnider2195** [comment]
It turns out the health check was causing the database exhaustion issue. [Related code is here](https://github.com/revsys/django-health-check/blob/593594f6ba9db7cd7fa02a30868133376cc302e4/health_check/mixins.py#L41)

If we take this approach for firing hooks we'll need to consider what happens when multiple changes are made to an object in a single "transaction" (a single request, or within a context manager, not database transaction). For example, if we delay webhook execution to the end of the transaction and in the transaction the object is updated and then deleted, do we fire a webhook for the update and the delete? If so, we'll need to cache the object to fire the webhook for the update since the object has already been deleted by the time we're firing the webhook.

**Comment by lampwins** [comment]
My preference would be that we focus on the final state of the object at the end of a "transaction." As you point out, today that is a web request or a manual invocation of the context manager. We have talked about adding support for the concept of long running web transactions in the future and I think this point is all the more reason to focus on the final state.

We just need to document it this way and users can then adjust their client access patterns if they need to.

**Comment by gsnider2195** [comment]
> My preference would be that we focus on the final state of the object at the end of a "transaction." As you point out, today that is a web request or a manual invocation of the context manager. We have talked about adding support for the concept of long running web transactions in the future and I think this point is all the more reason to focus on the final state.
> 
> We just need to document it this way and users can then adjust their client access patterns if they need to.

We discussed this earlier and came up with these tasks to get this across the finish line:

- [ ] The jobhook/webhook enqueue functions would need minor updates to no longer need access to the instance since all of the required data is already in the object change instance. (1 story point)
- [ ] Update the change logging to always look for an existing objectchange to update before creating a new one. So if an object is updated and then deleted inside of one web request, we just create a “deleted” objectchange instead of creating one for the update and one for the delete. (2 story points or potentially a bit more when thinking about test failures)

This would satisfy change logging only the "end state" and also give us a good path to implementing #4706. We would base these changes against develop as a bugfix, not planning to backport to 1.6. Do you see these tasks needing separate stories or implemented under #3015?

**Comment by gsnider2195** [comment]
Closing in favor of #4810

**Pull request closed without merging**
