### PR TITLE
Added Watchmedo command to worker container to allow container to res…

### PR DESCRIPTION
**Pull request by itdependsnetworks**
# Closes: DNE
# What's Changed

Added Watchmedo command to worker container to allow container to restart on file change.

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Confirmed (by changing a file) that it works

```bash
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | worker: Hitting Ctrl+C again will terminate all running tasks!
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | worker: Warm shutdown (MainProcess)
nautobot-celery_worker-1  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
nautobot-celery_worker-1  | absolutely not recommended!
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | Please specify a different user using the --uid option.
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | User information: uid=0 euid=0 gid=0 egid=0
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  |   uid=uid, euid=euid, gid=gid, egid=egid,
nautobot-celery_worker-1  |  
nautobot-celery_worker-1  |  -------------- celery@c08313901761 v5.2.7 (dawn-chorus)
nautobot-celery_worker-1  | --- ***** ----- 
nautobot-celery_worker-1  | -- ******* ---- Linux-5.10.124-linuxkit-aarch64-with-debian-11.5 2022-10-25 23:37:30
nautobot-celery_worker-1  | - *** --- * --- 
nautobot-celery_worker-1  | - ** ---------- [config]
nautobot-celery_worker-1  | - ** ---------- .> app:         nautobot:0xffffb2aad210
nautobot-celery_worker-1  | - ** ---------- .> transport:   redis://:**@redis:6379/0
nautobot-celery_worker-1  | - ** ---------- .> results:     redis://:**@redis:6379/0
nautobot-celery_worker-1  | - *** --- * --- .> concurrency: 5 (prefork)
nautobot-celery_worker-1  | -- ******* ---- .> task events: ON
nautobot-celery_worker-1  | --- ***** ----- 
nautobot-celery_worker-1  |  -------------- [queues]
nautobot-celery_worker-1  |                 .> celery           exchange=celery(direct) key=celery
nautobot-celery_worker-1  |                 
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | [tasks]
nautobot-celery_worker-1  |   . nautobot.extras.datasources.git.git_repository_diff_origin_and_local
nautobot-celery_worker-1  |   . nautobot.extras.datasources.git.pull_git_repository_and_refresh_data
nautobot-celery_worker-1  |   . nautobot.extras.jobs.run_job
nautobot-celery_worker-1  |   . nautobot.extras.jobs.scheduled_job_handler
nautobot-celery_worker-1  |   . nautobot.extras.tasks.delete_custom_field_data
nautobot-celery_worker-1  |   . nautobot.extras.tasks.process_webhook
nautobot-celery_worker-1  |   . nautobot.extras.tasks.provision_field
nautobot-celery_worker-1  |   . nautobot.extras.tasks.update_custom_field_choice_data
nautobot-celery_worker-1  |   . nautobot.utilities.tasks.get_releases
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | [2022-10-25 23:37:30,802: INFO/MainProcess] Connected to redis://:**@redis:6379/0
nautobot-celery_worker-1  | [2022-10-25 23:37:30,807: INFO/MainProcess] mingle: searching for neighbors
nautobot-celery_worker-1  | [2022-10-25 23:37:31,823: INFO/MainProcess] mingle: all alone
nautobot-celery_worker-1  | [2022-10-25 23:37:31,850: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:204: UserWarning: Using settings.DEBUG leads to a memory
nautobot-celery_worker-1  |             leak, never use this setting in production environments!
nautobot-celery_worker-1  |   leak, never use this setting in production environments!''')
nautobot-celery_worker-1  | 
nautobot-celery_worker-1  | [2022-10-25 23:37:31,850: INFO/MainProcess] celery@c08313901761 ready.
```


This is already installed via mkdocs

```bash
├── mkdocs >=1.3.0
│   ├── click >=3.3 
│   │   ├── colorama * 
│   │   └── importlib-metadata * 
│   │       ├── typing-extensions >=3.6.4 
│   │       └── zipp >=0.5 
│   ├── ghp-import >=1.0 
│   │   └── python-dateutil >=2.8.1 
│   │       └── six >=1.5 
│   ├── importlib-metadata >=4.3 (circular dependency aborted here)
│   ├── jinja2 >=2.10.2 
│   │   └── markupsafe >=2.0 
│   ├── markdown >=3.2.1,<3.4 
│   │   └── importlib-metadata >=4.4 (circular dependency aborted here)
│   ├── mergedeep >=1.3.4 
│   ├── packaging >=20.5 
│   │   └── pyparsing >=2.0.2,<3.0.5 || >3.0.5 
│   ├── pyyaml >=3.10 
│   ├── pyyaml-env-tag >=0.1 
│   │   └── pyyaml * (circular dependency aborted here)
│   └── watchdog >=2.0 
```

**Comment by glennmatthews** [comment]
Thanks for the PR! I think it would be good to add `watchdog` as an explicit dev-dependency just in case `mkdocs` ever changes its dependencies to no longer require it. It would also be good to update the documentation. It looks like for the `virtualenv` workflow we don't even have any documentation about running the Celery worker in development - we should add a section about that and document using `watchmedo` in that case for convenience and feature parity with the `docker-compose` workflow.

**Comment by itdependsnetworks** [comment]
I gave the docs updates the old college try

**Comment by itdependsnetworks** [comment]
Honestly, I don't know enough about poetry. Initially I tried `poetry add -D watchdog`, that created another group, so i moved it into the existing group, and then ran poetry lock. Perhaps I did not follow the correct way to do it.

**Comment by itdependsnetworks** [comment]
Thanks @glennmatthews!! Now I understand

**Review by bryanculver — APPROVED** [review]
Addressed merge conflicts. Should be GTG

**Pull request merged**
