### PR TITLE
Fix missing commas in task queue config example

### PR DESCRIPTION
**Pull request by ggidofalvy-tc**
### Fixes: Minor issue with task queue config documentation

I've noticed that the example docs didn't have a valid dict in them; two commas are missing.

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]
Good catch, and thank you for the fix!

**Comment by lampwins** [comment]
Thanks for catching that. If only Black could format the docs :)

**Review by lampwins — APPROVED** [review]

**Comment by jathanism** [comment]
Hmm... @ggidofalvy-tc would you mind force-pushing to this branch to kickoff the tests gain? Travis CI seems to be lost.

**Comment by ggidofalvy-tc** [comment]
All checks passed after a force-push. :heavy_check_mark:

**Comment by jathanism** [comment]
> All checks passed after a force-push. ✔️

Thank you for the contribution! 🙃

**Pull request merged**
