### PR TITLE
Adding http-keepalive uwsgi configuration

### PR DESCRIPTION
**Pull request by nniehoff**
### Fixes: #725 

Adding `http-keepalive = 1` resolves the remote disconnects reported in #725.

### CODE REVIEW

**Review by glennmatthews — APPROVED** [review]
Might it be good to add a note in nautobot/docs/installation/upgrading.md about adding this parameter to any existing `uwsgi.ini` that was previously in use?

**Comment by nniehoff** [comment]
> Might it be good to add a note in nautobot/docs/installation/upgrading.md about adding this parameter to any existing `uwsgi.ini` that was previously in use?

IMO there isn't a great place to put it in there at this point.  Should we create another section in there or maybe adding it to the release notes instead?

**Review by jathanism — APPROVED** [review]

**Comment by glennmatthews** [comment]
Probably adding a mention of this to the release-notes as an admonition would be appropriate.

**Comment by jvanderaa** [comment]
Confirmed that this has fixed in several environments. @jathanism @glennmatthews

**Comment by glennmatthews** [comment]
@jathanism Would you be willing to add the appropriate release-note admonition after merging this?

**Comment by jathanism** [comment]
> @jathanism Would you be willing to add the appropriate release-note admonition after merging this?

Was already planning to! 🤛

**Pull request merged**
